---
parameters:
  metatrader:
    data_path: C:\Users\Alpha\AppData\Roaming\MetaQuotes\Terminal
    expert_advisors:
      Bartolo:
        active: true
        # ESTRATEGIA_C
        inputs:
          Tiempo: 5, 1440, 5
      Fermin:
        active: false
      Prudencio:
        active: true
        inputs:
          # min, max, increment | single value | array
          Beneficio: 10, 50, 10
          Cobertura: 100, 2000, 50
          Distancia: 100, 1000, 50
          Exponencial: 'false'
          Multiplicador: 1
      Wilson:
        active: false
services:
  _defaults:
    autoconfigure: true
    autowire: true
  App\:
    exclude:
      - '../src/Kernel.php'
    resource: '../src/'
